kind: Service
apiVersion: v1
metadata:
  name: produect-service
spec:
  type: NodePort
  selector:
    app: spring-cloud-produect-service
  ports:
  - protocol: TCP
    port: 8093
    targetPort: 8093
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-produect-service
  labels:
    app: spring-cloud-produect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-produect-service
  template:
    metadata:
      labels:
        app: spring-cloud-produect-service
        version: latest
    spec:
      containers:
      - name: spring-cloud-produect-service
        image: 192.168.0.8:5000/product-service:latest
        ports:
        - name: http
          containerPort: 8093